#!/bin/bash

start() {
	/bin/Durex
	echo "starting durex service"
}

stop() {
	pkill Durex
	echo "stopping durex service"
}

status() {
	echo "getting status of service"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart|reload)
        stop
        start
        ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|reload}"
    exit 1
esac
exit 0
